In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

2.0.0
2.2.4-tf


1.keras导入 2.构建模型 3.训练和评估 4.

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [3]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# tf.keras.layers中网络配置：

# activation：设置层的激活函数。此参数由内置函数的名称指定，或指定为可调用对象。默认情况下，系统不会应用任何激活函数。

# kernel_initializer 和 bias_initializer：创建层权重（核和偏差）的初始化方案。此参数是一个名称或可调用对象，默认为 "Glorot uniform" 初始化器。

# kernel_regularizer 和 bias_regularizer：应用层权重（核和偏差）的正则化方案，例如 L1 或 L2 正则化。默认情况下，系统不会应用正则化函数。

In [4]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [5]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

In [6]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 1s 1ms/sample - loss: 13.2674 - categorical_accuracy: 0.0990 - val_loss: 14.6238 - val_categorical_accuracy: 0.1150
Epoch 2/10
1000/1000 [==============================] - 0s 26us/sample - loss: 16.1404 - categorical_accuracy: 0.0920 - val_loss: 18.6274 - val_categorical_accuracy: 0.1200
Epoch 3/10
1000/1000 [==============================] - 0s 28us/sample - loss: 20.5029 - categorical_accuracy: 0.0960 - val_loss: 22.9680 - val_categorical_accuracy: 0.1100
Epoch 4/10
1000/1000 [==============================] - 0s 26us/sample - loss: 25.1744 - categorical_accuracy: 0.0990 - val_loss: 28.4597 - val_categorical_accuracy: 0.1100
Epoch 5/10
1000/1000 [==============================] - 0s 25us/sample - loss: 31.3614 - categorical_accuracy: 0.1050 - val_loss: 35.1096 - val_categorical_accuracy: 0.1250
Epoch 6/10
1000/1000 [==============================] - 0s 25us/sample - loss: 38.3097 - 

In [7]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

Train for 30 steps, validate for 3 steps
Epoch 1/10
30/30 [==============================] - 0s 11ms/step - loss: 110.0215 - categorical_accuracy: 0.0969 - val_loss: 139.1903 - val_categorical_accuracy: 0.1354
Epoch 2/10
30/30 [==============================] - 0s 2ms/step - loss: 164.9663 - categorical_accuracy: 0.0887 - val_loss: 194.9998 - val_categorical_accuracy: 0.1354
Epoch 3/10
30/30 [==============================] - 0s 2ms/step - loss: 224.0970 - categorical_accuracy: 0.0940 - val_loss: 260.7771 - val_categorical_accuracy: 0.1250
Epoch 4/10
30/30 [==============================] - 0s 1ms/step - loss: 289.4080 - categorical_accuracy: 0.0940 - val_loss: 323.0591 - val_categorical_accuracy: 0.1146
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - loss: 347.6128 - categorical_accuracy: 0.1058 - val_loss: 373.7799 - val_categorical_accuracy: 0.1042
Epoch 6/10
30/30 [==============================] - 0s 2ms/step - loss: 392.2204 - categorical_accuracy: 0.0855 - val_

In [8]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)
# predict
result = model.predict(test_x, batch_size=32)
print(result)

1000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

30/30 [==============================] - 0s 800us/step - loss: 420.0971 - categorical_accuracy: 0.0885
[[0.02796429 0.         0.         ... 0.12218518 0.06216278 0.21444167]
 [0.02965079 0.         0.         ... 0.17673384 0.0800501  0.25941625]
 [0.02274294 0.         0.         ... 0.16772093 0.04435491 0.24095404]
 ...
 [0.01362843 0.         0.         ... 0.1819905  0.04148944 0.28491667]
 [0.01785827 0.         0.         ... 0.20942819 0.06456181 0.21418536]
 [0.01149021 0.         0.         ... 0.11559463 0.09648865 0.08674563]]


In [9]:
input_x = tf.keras.Input(shape=(72,))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)

model = tf.keras.Model(inputs=input_x, outputs=pred)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 353us/sample - loss: 12.2146 - accuracy: 0.0920
Epoch 2/5
1000/1000 [==============================] - 0s 41us/sample - loss: 16.7991 - accuracy: 0.1020
Epoch 3/5
1000/1000 [==============================] - 0s 40us/sample - loss: 34.2458 - accuracy: 0.1040
Epoch 4/5
1000/1000 [==============================] - 0s 40us/sample - loss: 64.9666 - accuracy: 0.1100
Epoch 5/5
1000/1000 [==============================] - 0s 40us/sample - loss: 110.7190 - accuracy: 0.1080


### 高级模型构建

In [12]:
input_x = tf.keras.Input(shape=(72,))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)

model = tf.keras.Model(inputs=input_x, outputs=pred)
model.compile(
    optimizer = tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.categorical_crossentropy,
    metrics = ['accuracy']
)
model.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 1s 606us/sample - loss: 12.3646 - accuracy: 0.0990
Epoch 2/5
1000/1000 [==============================] - 0s 41us/sample - loss: 15.9258 - accuracy: 0.0890
Epoch 3/5
1000/1000 [==============================] - 0s 39us/sample - loss: 27.7779 - accuracy: 0.0950
Epoch 4/5
1000/1000 [==============================] - 0s 42us/sample - loss: 53.3487 - accuracy: 0.1150
Epoch 5/5
1000/1000 [==============================] - 0s 38us/sample - loss: 98.9946 - accuracy: 0.1160


In [17]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.layer1 = layers.Dense(32, activation='relu')
        self.layer2 = layers.Dense(num_classes, activation='softmax')
    def call(self, inputs):
        h1 = self.layer1(inputs)
        out = self.layer2(h1)
        return out
    
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.num_classes
        return tf.TensorShape(shape)
    
model = MyModel(num_classes=10)
model.compile(
    optimizer = tf.keras.optimizers.RMSprop(0.001),
    loss = tf.keras.losses.categorical_crossentropy,
    metrics = ['accuracy']
)

model.fit(train_x, train_y, batch_size=16, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 461us/sample - loss: 13.3685 - accuracy: 0.0980
Epoch 2/5
1000/1000 [==============================] - 0s 74us/sample - loss: 17.1370 - accuracy: 0.1000
Epoch 3/5
1000/1000 [==============================] - 0s 75us/sample - loss: 19.8739 - accuracy: 0.0920
Epoch 4/5
1000/1000 [==============================] - 0s 76us/sample - loss: 22.0143 - accuracy: 0.0920
Epoch 5/5
1000/1000 [==============================] - 0s 76us/sample - loss: 24.3250 - accuracy: 0.0870
